[package]
name = "desktoporz"
version = "0.2.1"
edition = "2021"
description = "Open source DesktopOK clone: save and restore Windows desktop icon layouts"
license = "MIT"
include = [
    "src/**/*",
    "build.rs",
    "langs/**/*",
    "Cargo.toml",
    "README.md",
]

[[bin]]
name = "DesktopORZ"
path = "src/main.rs"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Registry",
    "Win32_Security",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
